/**————————————————————————————————————————————————————————————————————————————————————————————————————————
* @Name             CourseList_Controller
*————————————————————————————————————————————————————————————————————————————————————————————————————————
* @Description
* Controller class for LWC component courseList_lwc to fetch all the courses & the courses that 
* the Current User have access which are in the system.
*————————————————————————————————————————————————————————————————————————————————————————————————————————
**/

public with sharing class CourseList_Controller {

 
}